import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { RuleFinding } from "../types.js";
import type { SentinelReportFile } from "./types.js";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderFinding(finding: RuleFinding): string {
  return `
    <article class="issue issue--${finding.severity}">
      <header>
        <span class="badge">${escapeHtml(finding.severity)}</span>
        <strong>${escapeHtml(finding.component ?? "Project")}</strong>
      </header>
      <p class="problem">${escapeHtml(finding.problem)}</p>
      <p class="suggestion"><strong>Fix:</strong> ${escapeHtml(finding.suggestion)}</p>
      <p class="explanation">${escapeHtml(finding.explanation)}</p>
    </article>`;
}

export function renderHtmlReport(report: SentinelReportFile): string {
  const { meta, intelligence, componentGraph, runtime } = report;
  const graphMeta = componentGraph?.meta;
  const findings = intelligence.findings;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vue Sentinel X Report</title>
  <style>
    :root { font-family: system-ui, sans-serif; color: #e7ecf3; background: #0f1419; }
    body { margin: 0; padding: 1.5rem; max-width: 960px; margin-inline: auto; }
    h1 { font-size: 1.5rem; margin: 0 0 0.25rem; }
    .meta { color: #94a3b8; font-size: 0.85rem; margin-bottom: 1.5rem; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 0.75rem; margin-bottom: 1.5rem; }
    .stat { background: #1a2332; padding: 0.75rem; border-radius: 8px; border: 1px solid #2d3a4f; }
    .stat span { display: block; font-size: 0.7rem; color: #94a3b8; }
    .stat strong { font-size: 1.2rem; }
    .issues { display: flex; flex-direction: column; gap: 0.75rem; }
    .issue { background: #1a2332; border-radius: 8px; padding: 1rem; border-left: 4px solid #3b82f6; }
    .issue--error { border-left-color: #ef4444; }
    .issue--warning { border-left-color: #f59e0b; }
    .badge { font-size: 0.65rem; text-transform: uppercase; margin-right: 0.5rem; opacity: 0.8; }
    .problem { margin: 0.5rem 0; }
    .suggestion, .explanation { font-size: 0.9rem; color: #cbd5e1; margin: 0.35rem 0; }
    footer { margin-top: 2rem; font-size: 0.75rem; color: #64748b; }
  </style>
</head>
<body>
  <h1>Vue Sentinel X Report</h1>
  <p class="meta">${escapeHtml(meta.projectRoot)} · ${escapeHtml(meta.generatedAt)} · ${escapeHtml(meta.source)}</p>

  <section class="stats">
    <div class="stat"><span>Components</span><strong>${graphMeta?.componentCount ?? "—"}</strong></div>
    <div class="stat"><span>Graph edges</span><strong>${graphMeta?.edgeCount ?? "—"}</strong></div>
    <div class="stat"><span>Issues</span><strong>${findings.length}</strong></div>
    <div class="stat"><span>Memory warnings</span><strong>${runtime?.memory?.warnings.length ?? 0}</strong></div>
    <div class="stat"><span>Slow components</span><strong>${runtime?.performance?.slowComponentCount ?? 0}</strong></div>
  </section>

  <h2>Summary</h2>
  <p>${escapeHtml(intelligence.summary)}</p>

  <h2>Issues</h2>
  <div class="issues">
    ${findings.length ? findings.map(renderFinding).join("") : "<p>No issues detected.</p>"}
  </div>

  <footer>
    Generated by Vue Sentinel X v${escapeHtml(meta.version)}.
    Open <code>analysis/sentinel-report.json</code> for machine-readable data.
  </footer>
</body>
</html>`;
}

export async function writeHtmlReport(
  filePath: string,
  report: SentinelReportFile,
): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, renderHtmlReport(report), "utf8");
}
